name: Android CI Dev workflow

on:
  push:
    branches: 
        - develop
        - 'release/**'  # Push events to branches matching refs/heads/release/10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'

    - uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper
        cache-read-only: false
        gradle-home-cache-cleanup: true
        
    - name: Build Dev
      run: ./gradlew assembleRelease --no-configuration-cache
              
    - name: Upload Dev build to Firebase distribution
      if: ${{ github.event_name == 'push' }}
      run: ./gradlew appDistributionUploadRelease